version: "3"

silent: true

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  lint:
    desc: "Run golangci-lint"
    deps: [lint-install]
    cmds:
      - golangci-lint run

  lint-install:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    status:
      - command -v golangci-lint

  lint-list:
    desc: "Run golangci-lint linters (print enabled & disabled linters)"
    deps: [lint-install]
    cmds:
      - golangci-lint linters

  test:
    desc: "Run tests"
    cmds:
      - mkdir -p bin
      - |
        go test -coverprofile bin/cover.out \
          $(go list ./... | grep -v /examples/ | grep -v /test | grep -v /internal/ | grep -v /mock)
    sources:
      - ./**/*.go
      - go.mod
    generates:
      - bin/cover.out

  cover:
    desc: "Run tests & show coverage"
    deps:
      - test
    cmds:
      - go tool cover -func bin/cover.out

  race:
    desc: "Run tests with race flag"
    cmds:
      - go test -race -count=1 ./...

  bench:
    desc: "Run benchmarks"
    cmds:
      - go test -bench=. -benchtime=10s -benchmem

  build-examples:
    desc: "Build examples into bin folder"
    cmds:
      - go build -o bin/ ./examples/*

  pre-commit:
    desc: "Run tests, linter and build examples"
    cmds:
      - task: test
      - task: lint
      - task: build-examples

  generate:
    desc: "Generate (used for mock generation)"
    cmds:
      - go generate ./...

  mock-install:
    desc: "Install mockgen"
    cmds:
      - go install github.com/golang/mock/mockgen@latest
    status:
      - command -v mockgen

  generator:
    desc: "Run specific generation"
    cmds:
      - go run ./internal/generator {{.CLI_ARGS}}

  generator-all:
    desc: "Run all generators"
    cmds:
      - task: generator
        vars:
          CLI_ARGS: types types-tests types-setters types-setters-tests methods methods-tests methods-setters methods-setters-tests

  generator-clean-up:
    desc: "Remove generated files"
    cmds:
      - rm *.generated
