name: CI
'on':
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    golang:
        name: Golang
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.16

            - name: Install linter
              run: make lint-install

            - name: Run linter
              run: make lint
