name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.16
                
    linter:
        name: Linter
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Install linter
              run: make lint-install

            - name: Run linter
              run: make lint

