name: Race Testing

on:
  schedule:
    - cron: "0 7 4 * *"
  workflow_dispatch: { }

permissions:
  contents: read

jobs:
  race:
    name: Race Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true

      - name: Run race tests
        run: go test -race -count=128 $(go list ./... | grep -v /examples | grep -v /internal | grep -v /mock)
